front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:FrontHomePage:renderHomepage }

contact_ajax_request:
    path: /send_form
    defaults: { _controller: FrontBundle:FrontHomePage:sendForm }
    methods: [post]
